version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: flagger-api-postgres
    environment:
      POSTGRES_DB: flaggerdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  server:
    build:
      context: .
      dockerfile: Dockerfile.local
    command: go run ./...
    container_name: flagger-api-server
    environment:
      FLAGGERAPI_HOSTNAME: localhost
      FLAGGERAPI_PORT: 8080
      FLAGGERAPI_POSTGRES_HOSTNAME: host.docker.internal
      FLAGGERAPI_POSTGRES_PORT: 5432
      FLAGGERAPI_POSTGRES_USERNAME: postgres
      FLAGGERAPI_POSTGRES_PASSWORD: postgres
      FLAGGERAPI_POSTGRES_DATABASE_NAME: flaggerdb
      FLAGGERAPI_MAIL_CLIENT_TYPE: console
    ports:
      - 8080:8080
    depends_on:
      - postgres
    volumes:
      - ./cmd:/app/cmd
      - ./internal:/app/internal
      - ./pkg:/app/pkg
      - ./templates:/app/templates
