version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: flagger-api-postgres
    environment:
      POSTGRES_DB: ${FLAGGERAPI_POSTGRES_DATABASE_NAME:-flaggerdb}
      POSTGRES_USER: ${FLAGGERAPI_POSTGRES_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${FLAGGERAPI_POSTGRES_PASSWORD:-postgres}
    ports:
      - ${FLAGGERAPI_POSTGRES_PORT:-5432}:${FLAGGERAPI_POSTGRES_PORT:-5432}
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  server:
    build:
      context: .
      dockerfile: Dockerfile.local
    command: go run ./...
    container_name: flagger-api-server
    environment:
      FLAGGERAPI_HOSTNAME: ${FLAGGERAPI_HOSTNAME:-0.0.0.0}
      FLAGGERAPI_PORT: ${FLAGGERAPI_PORT:-8080}
      FLAGGERAPI_SECRET_KEY: ${FLAGGERAPI_SECRET_KEY:-DEADBEEF}
      FLAGGERAPI_HASHING_COST: ${FLAGGERAPI_HASHING_COST:-14}
      FLAGGERAPI_FRONTEND_BASE_URL: ${FLAGGERAPI_FRONTEND_BASE_URL:-http://localhost:3000}
      FLAGGERAPI_FRONTEND_ACTIVATION_ROUTE: ${FLAGGERAPI_FRONTEND_ACTIVATION_ROUTE:-/signup/activate/%s}
      FLAGGERAPI_AUTH_ACCESS_LIFETIME: ${FLAGGERAPI_AUTH_ACCESS_LIFETIME:-30}
      FLAGGERAPI_AUTH_REFRESH_LIFETIME: ${FLAGGERAPI_AUTH_REFRESH_LIFETIME:-43800}
      FLAGGERAPI_ACTIVATION_LIFETIME: ${FLAGGERAPI_ACTIVATION_LIFETIME:-43800}
      FLAGGERAPI_POSTGRES_HOSTNAME: ${FLAGGERAPI_POSTGRES_HOSTNAME:-host.docker.internal}
      FLAGGERAPI_POSTGRES_PORT: ${FLAGGERAPI_POSTGRES_PORT:-5432}
      FLAGGERAPI_POSTGRES_USERNAME: ${FLAGGERAPI_POSTGRES_USERNAME:-postgres}
      FLAGGERAPI_POSTGRES_PASSWORD: ${FLAGGERAPI_POSTGRES_PASSWORD:-postgres}
      FLAGGERAPI_POSTGRES_DATABASE_NAME: ${FLAGGERAPI_POSTGRES_DATABASE_NAME:-flaggerdb}
      FLAGGERAPI_SMTP_HOSTNAME: ${FLAGGERAPI_SMTP_HOSTNAME:-smtp.gmail.com}
      FLAGGERAPI_SMTP_PORT: ${FLAGGERAPI_SMTP_PORT:-587}
      FLAGGERAPI_SMTP_USERNAME: ${FLAGGERAPI_SMTP_USERNAME:-}
      FLAGGERAPI_SMTP_PASSWORD: ${FLAGGERAPI_SMTP_PASSWORD:-}
      FLAGGERAPI_MAIL_CLIENT_TYPE: ${FLAGGERAPI_MAIL_CLIENT_TYPE:-console}
    ports:
      - ${FLAGGERAPI_PORT:-8080}:${FLAGGERAPI_PORT:-8080}
    depends_on:
      - postgres
    volumes:
      - ./cmd:/app/cmd
      - ./internal:/app/internal
      - ./pkg:/app/pkg
